# Debug configuration for rapid testing of visualization logging

model:
  model_type: genesis_v2
  K_steps: 5
  in_chnls: 3
  img_size: 64
  feat_dim: 64
  kernel: gaussian
  broadcast_size: 4
  add_coords_every_layer: false
  normal_std: 0.7
  lstm_hidden_dim: 256
  detach_recon_masks: true
training:
  batch_size: 4
  max_steps: 11  # Run for just over one validation cycle
  learning_rate: 0.001
  weight_decay: 0.0
  use_lr_scheduler: true
  lr_schedule_patience: 5
  lr_schedule_factor: 0.5
  lr_schedule_min_lr: 1.0e-06
  use_mask_kl_loss: true
  elbo_divergence_threshold: 100000000.0
  geco_goal: 0.5655
  geco_lr: 1.0e-05
  geco_alpha: 0.99
  geco_beta_init: 1.0
  geco_beta_min: 1.0e-10
  geco_speedup: 10.0
data:
  dataset: d_sprites
  variable_size: false
  is_discrete: false
  seed: 42
# Experiment Metadata
project_name: "genesis_v2_debug"
run_name: "debug_visualization_final_test"
save_dir: ./experiments
# Logging & Checkpointing
log_every_n_steps: 10
val_check_interval: 10 # Validate every 10 steps
save_top_k: 1
monitor_metric: "loss_val/total_loss"
monitor_mode: min
